version: '3.8'

services:
  app-hsl:
    container_name: app-hsl
    image: node
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    # restart: always
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres-hsl
    volumes:
      - ./:/usr/app/
      - ./db:/usr/app/db
    # networks:
    #   - hsl_net

  postgres-hsl:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: postgres-hsl
    image: postgres:15.3-alpine3.18
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /data/postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    # networks:
    #   - hsl_net
    restart: unless-stopped

volumes:
  pgdata: {}
# networks:
#   hsl_net:
#     driver: bridge
