version: '3.8'

services:
  db:
    container_name: postgres-hsl
    image: postgres:14.0-alpine
    restart: always
    environment:
      - POSTGRES_USER=${TYPEORM_USERNAME}
      - POSTGRES_PASSWORD=${TYPEORM_PASSWORD}
      - POSTGRES_DB=${TYPEORM_DATABASE}
    volumes:
      - ./pgdata:/var/lib/postgesql/data
    ports:
      - ${TYPEORM_PORT}:${TYPEORM_PORT}
